GET http://localhost:3000/subscribers/6537b23e37cb1c3880844c46

###

POST http://localhost:3000/subscribers
Content-Type: application/json

{
    "name": "Derek",
    "subscribedToChannel": "teatime"
}


###

DELETE http://localhost:3000/subscribers/6537c297c38b09e48f23b86e

###

PATCH http://localhost:3000/subscribers/6537c35cd51f28a19f175631
Content-Type: application/json

{
    "name": "NewName"
}